version: '2'

services:
  app:
    image: 'algeps_task_management_system'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tms-postgres
      - SPRING_DATASOURCE_USERNAME=tms-postgres
      - SPRING_DATASOURCE_PASSWORD=tms-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_USER=tms-postgres
      - POSTGRES_PASSWORD=tms-postgres